Ch10155/callstats android library integration in apprtc android demo app
callstats-io/AppRTCMobile_android pull request #1
Opened 2018-10-08 12:39 UTC by pallab-gain

https://app.clubhouse.io/callstatsio/story/10155/callstats-android-library-integration-in-apprtc-android-demo-app

**Callstats android library integration in AppRTC android demo app**

2018-10-08 13:02 UTC, karthikbr82 requested changes

2018-10-08 13:02 UTC, karthikbr82 commented on README.md
> +These instructions will help you run the apprtc android demo application with csio integration. See notes on how you will get
change csio to callstats.io

2018-10-08 13:02 UTC, karthikbr82 commented on README.md
> +callstarts library related credentials to run the application.
callstarts to callstats

2018-10-08 13:02 UTC, karthikbr82 commented on README.md
> +
can you write some description about the integration steps?

2018-10-08 13:02 UTC, karthikbr82 commented on app/src/main/java/org/appspot/apprtc/csio/CsioSHIM.java
> +
can we use camel case for naming?

2018-10-08 14:25 UTC, pallab-gain commented on README.md
> +
Thanks. I just added integration steps, and pushed for your review.

2018-10-09 07:12 UTC, pallab-gain commented
@karthikbr82 I updated the readme. Can you please take a look, and let me know if we need some updates or fix ?

- Add integration steps
- Some other readme, and code fix based on your previous feedback.

2018-10-09 07:21 UTC, karthikbr82 commented on app/src/main/java/org/appspot/apprtc/csio/CSIOEvents.java
> +}
use camel case for function naming.

2018-10-09 07:41 UTC, karthikbr82 approved these changes

2018-10-09 08:06 UTC, merged